defaults:
  - _self_
  - camera
  - network
  - robot: xela_hand_franka
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: /home/ademi/hermes/data/teleoperation_dataset/collect_ball_20241122a
demo_num: 1
sim_env: false
is_xela: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .
